#############################################################################
# Makefile for building: make
# Generated by qmake (2.01a) (Qt 4.8.6) on: Thu Jul 9 12:38:06 2015
# Project:  make.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile make.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-cudaHOG \
		sub-RealPDT

cudaHOG//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) cudaHOG/ || $(MKDIR) cudaHOG/ 
	cd cudaHOG/ && $(QMAKE) /home/dapopesc/src/TrackingAlgorithm/cudaHOG/cudaHOG.pro -o $(MAKEFILE)
sub-cudaHOG-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) cudaHOG/ || $(MKDIR) cudaHOG/ 
	cd cudaHOG/ && $(QMAKE) /home/dapopesc/src/TrackingAlgorithm/cudaHOG/cudaHOG.pro -o $(MAKEFILE)
sub-cudaHOG: cudaHOG//$(MAKEFILE) FORCE
	cd cudaHOG/ && $(MAKE) -f $(MAKEFILE)
sub-cudaHOG-make_default: cudaHOG//$(MAKEFILE) FORCE
	cd cudaHOG/ && $(MAKE) -f $(MAKEFILE) 
sub-cudaHOG-make_first: cudaHOG//$(MAKEFILE) FORCE
	cd cudaHOG/ && $(MAKE) -f $(MAKEFILE) first
sub-cudaHOG-all: cudaHOG//$(MAKEFILE) FORCE
	cd cudaHOG/ && $(MAKE) -f $(MAKEFILE) all
sub-cudaHOG-clean: cudaHOG//$(MAKEFILE) FORCE
	cd cudaHOG/ && $(MAKE) -f $(MAKEFILE) clean
sub-cudaHOG-distclean: cudaHOG//$(MAKEFILE) FORCE
	cd cudaHOG/ && $(MAKE) -f $(MAKEFILE) distclean
sub-cudaHOG-install_subtargets: cudaHOG//$(MAKEFILE) FORCE
	cd cudaHOG/ && $(MAKE) -f $(MAKEFILE) install
sub-cudaHOG-uninstall_subtargets: cudaHOG//$(MAKEFILE) FORCE
	cd cudaHOG/ && $(MAKE) -f $(MAKEFILE) uninstall
RealPDT//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) RealPDT/ || $(MKDIR) RealPDT/ 
	cd RealPDT/ && $(QMAKE) /home/dapopesc/src/TrackingAlgorithm/RealPDT/RealPDT.pro -o $(MAKEFILE)
sub-RealPDT-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) RealPDT/ || $(MKDIR) RealPDT/ 
	cd RealPDT/ && $(QMAKE) /home/dapopesc/src/TrackingAlgorithm/RealPDT/RealPDT.pro -o $(MAKEFILE)
sub-RealPDT: RealPDT//$(MAKEFILE) FORCE
	cd RealPDT/ && $(MAKE) -f $(MAKEFILE)
sub-RealPDT-make_default: RealPDT//$(MAKEFILE) FORCE
	cd RealPDT/ && $(MAKE) -f $(MAKEFILE) 
sub-RealPDT-make_first: RealPDT//$(MAKEFILE) FORCE
	cd RealPDT/ && $(MAKE) -f $(MAKEFILE) first
sub-RealPDT-all: RealPDT//$(MAKEFILE) FORCE
	cd RealPDT/ && $(MAKE) -f $(MAKEFILE) all
sub-RealPDT-clean: RealPDT//$(MAKEFILE) FORCE
	cd RealPDT/ && $(MAKE) -f $(MAKEFILE) clean
sub-RealPDT-distclean: RealPDT//$(MAKEFILE) FORCE
	cd RealPDT/ && $(MAKE) -f $(MAKEFILE) distclean
sub-RealPDT-install_subtargets: RealPDT//$(MAKEFILE) FORCE
	cd RealPDT/ && $(MAKE) -f $(MAKEFILE) install
sub-RealPDT-uninstall_subtargets: RealPDT//$(MAKEFILE) FORCE
	cd RealPDT/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: make.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile make.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile make.pro

qmake_all: sub-cudaHOG-qmake_all sub-RealPDT-qmake_all FORCE

make_default: sub-cudaHOG-make_default sub-RealPDT-make_default FORCE
make_first: sub-cudaHOG-make_first sub-RealPDT-make_first FORCE
all: sub-cudaHOG-all sub-RealPDT-all FORCE
clean: sub-cudaHOG-clean sub-RealPDT-clean FORCE
distclean: sub-cudaHOG-distclean sub-RealPDT-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-cudaHOG-install_subtargets sub-RealPDT-install_subtargets FORCE
uninstall_subtargets: sub-cudaHOG-uninstall_subtargets sub-RealPDT-uninstall_subtargets FORCE

sub-cudaHOG-check: cudaHOG/$(MAKEFILE)
	cd cudaHOG/ && $(MAKE) -f $(MAKEFILE) check
sub-RealPDT-check: RealPDT/$(MAKEFILE)
	cd RealPDT/ && $(MAKE) -f $(MAKEFILE) check
check: sub-cudaHOG-check sub-RealPDT-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

